from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('', views.homePage, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('upload_post/', views.upload_post, name='upload_post'),
    path('comment/<int:post_id>/', views.comment, name='comment'),
    path('delete_comment/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('profileview/', views.ProfilePage, name='profileview'),
    path('view_profile/<int:user_id>/', views.UserProfilePage, name='view_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('update-profile-picture/', views.update_profile_picture, name='update_profile_picture'),
    path('update-cover-picture/', views.update_cover_picture, name='update_cover_picture'),
    path('about/', views.AboutPage, name='about'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('edit_post/<int:post_id>/', views.edit_post_content, name='edit_post_content'),
    path('inbox/', views.inbox, name='inbox'),
    path('send-message/<int:recipient_id>/', views.send_message, name='send-message'),
    path('conversation/<int:conversation_id>/', views.conversation_detail, name='conversation-detail'),
    path('send-message/<int:recipient_id>/', views.send_message, name='send_message'),
    path('notifications/', views.notification_view, name='notifications'),
    path('accept_friend_request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('reject_friend_request/<int:request_id>/', views.reject_friend_request, name='reject_friend_request'),
    path('friends_list/', views.friends_list, name='friends_list'),
    path('unfriend/<int:user_id>/', views.unfriend, name='unfriend'),
    path('notifications/', views.dashboard, name='notifications'),
path('edit-post-ajax/<int:post_id>/', views.edit_post_ajax, name='edit_post_ajax'),
path('friend-request/send/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
path('friend-request/cancel/<int:request_id>/', views.cancel_friend_request, name='cancel_friend_request'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('delete_conversation/<int:conversation_id>/', views.delete_conversation, name='delete_conversation'),
]