# Generated by Django 5.1.4 on 2025-01-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_picture', models.ImageField(blank=True, default='profile_pictures/cover.jpg', null=True, upload_to='cover_pictures/')),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/pic_def.jpg', null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(blank=True, default=' Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the', max_length=100, null=True)),
                ('b_day', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('phone_number', models.CharField(blank=True, default='0000000000', max_length=20, null=True)),
                ('address', models.CharField(blank=True, default='No Address', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10, null=True)),
                ('total_likes', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
