# Generated by Django 5.1.4 on 2025-01-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_profile_picture_alter_user_f_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_post',
            name='image',
        ),
    ]
